-- events_tags middle table
CREATE TABLE public.events_tags (
    event_tag_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    event_id BIGINT NOT NULL REFERENCES public.events(event_id) ON DELETE CASCADE,
    tag_id BIGINT NOT NULL REFERENCES public.tags(tag_id) ON DELETE CASCADE,
    display_order INTEGER NOT NULL DEFAULT 0,

    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    deleted_at TIMESTAMPTZ DEFAULT NULL
);

-- indexes
CREATE UNIQUE INDEX idx_events_tags_unique_active 
ON public.events_tags(event_id, tag_id) 
WHERE deleted_at IS NULL;

CREATE INDEX idx_events_tags_display_order ON public.events_tags(display_order DESC);
CREATE INDEX idx_events_tags_event_id ON public.events_tags(event_id);
CREATE INDEX idx_events_tags_tag_id ON public.events_tags(tag_id);

-- trigger
CREATE TRIGGER update_events_tags
    BEFORE UPDATE ON public.events_tags
    FOR EACH ROW
    EXECUTE FUNCTION update_at();

-- security
ALTER TABLE public.events_tags ENABLE ROW LEVEL SECURITY;
CREATE POLICY "No direct access" ON public.events_tags FOR ALL USING (false);
REVOKE ALL ON public.events_tags FROM public;