-- events_performers middle table
CREATE TABLE public.events_performers (
    event_performer_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    event_id BIGINT NOT NULL REFERENCES public.events(event_id) ON DELETE CASCADE,
    performer_id BIGINT NOT NULL REFERENCES public.performers(performer_id) ON DELETE CASCADE,
    display_order INTEGER NOT NULL DEFAULT 0,

    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    deleted_at TIMESTAMPTZ DEFAULT NULL
);

-- indexes
CREATE UNIQUE INDEX idx_events_performers_unique_active 
ON public.events_performers(event_id, performer_id) 
WHERE deleted_at IS NULL;

CREATE INDEX idx_events_performers_display_order ON public.events_performers(display_order DESC);
CREATE INDEX idx_events_performers_event_id ON public.events_performers(event_id);
CREATE INDEX idx_events_performers_performer_id ON public.events_performers(performer_id);

-- trigger
CREATE TRIGGER update_events_performers
    BEFORE UPDATE ON public.events_performers
    FOR EACH ROW
    EXECUTE FUNCTION update_at();

-- security
ALTER TABLE public.events_performers ENABLE ROW LEVEL SECURITY;
CREATE POLICY "No direct access" ON public.events_performers FOR ALL USING (false);
REVOKE ALL ON public.events_performers FROM public;