-- events_venues middle table
CREATE TABLE public.events_venues (
    event_venue_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    event_id BIGINT NOT NULL REFERENCES public.events(event_id) ON DELETE CASCADE,
    venue_id BIGINT NOT NULL REFERENCES public.venues(venue_id) ON DELETE CASCADE,
    display_order INTEGER NOT NULL DEFAULT 0,

    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    deleted_at TIMESTAMPTZ DEFAULT NULL
);

-- indexes
CREATE UNIQUE INDEX idx_events_venues_unique_active 
ON public.events_venues(event_id, venue_id) 
WHERE deleted_at IS NULL;

CREATE INDEX idx_events_venues_display_order ON public.events_venues(display_order DESC);
CREATE INDEX idx_events_venues_event_id ON public.events_venues(event_id);
CREATE INDEX idx_events_venues_venue_id ON public.events_venues(venue_id);

-- trigger
CREATE TRIGGER update_events_venues
    BEFORE UPDATE ON public.events_venues
    FOR EACH ROW
    EXECUTE FUNCTION update_at();

-- security
ALTER TABLE public.events_venues ENABLE ROW LEVEL SECURITY;
CREATE POLICY "No direct access" ON public.events_venues FOR ALL USING (false);
REVOKE ALL ON public.events_venues FROM public;
