-- events_slots middle table
CREATE TABLE public.events_slots (
    event_slot_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    event_id BIGINT NOT NULL REFERENCES public.events(event_id) ON DELETE CASCADE,
    slot_id BIGINT NOT NULL REFERENCES public.slots(slot_id) ON DELETE CASCADE,
    display_order INTEGER NOT NULL DEFAULT 0,

    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    deleted_at TIMESTAMPTZ DEFAULT NULL
);

-- indexes
CREATE UNIQUE INDEX idx_events_slots_unique_active 
ON public.events_slots(event_id, slot_id) 
WHERE deleted_at IS NULL;

CREATE INDEX idx_events_slots_display_order ON public.events_slots(display_order DESC);
CREATE INDEX idx_events_slots_event_id ON public.events_slots(event_id);
CREATE INDEX idx_events_slots_slot_id ON public.events_slots(slot_id);

-- trigger
CREATE TRIGGER update_events_slots
    BEFORE UPDATE ON public.events_slots
    FOR EACH ROW
    EXECUTE FUNCTION update_at();

-- security
ALTER TABLE public.events_slots ENABLE ROW LEVEL SECURITY;
CREATE POLICY "No direct access" ON public.events_slots FOR ALL USING (false);
REVOKE ALL ON public.events_slots FROM public;