-- tags_categories middle table
CREATE TABLE public.tags_categories (
    tag_category_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    tag_id BIGINT NOT NULL REFERENCES public.tags(tag_id) ON DELETE CASCADE,
    category_id BIGINT NOT NULL REFERENCES public.categories(category_id) ON DELETE CASCADE,
    display_order INTEGER NOT NULL DEFAULT 0,

    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    deleted_at TIMESTAMPTZ DEFAULT NULL
);

-- indexes
CREATE UNIQUE INDEX idx_tags_categories_unique_active 
ON public.tags_categories(tag_id, category_id) 
WHERE deleted_at IS NULL;

CREATE INDEX idx_tags_categories_display_order ON public.tags_categories(display_order DESC);
CREATE INDEX idx_tags_categories_tag_id ON public.tags_categories(tag_id);
CREATE INDEX idx_tags_categories_category_id ON public.tags_categories(category_id);

-- trigger
CREATE TRIGGER update_tags_categories
    BEFORE UPDATE ON public.tags_categories
    FOR EACH ROW
    EXECUTE FUNCTION update_at();

-- security
ALTER TABLE public.tags_categories ENABLE ROW LEVEL SECURITY;
CREATE POLICY "No direct access" ON public.tags_categories FOR ALL USING (false);
REVOKE ALL ON public.tags_categories FROM public;