-- venues_organizations middle table
CREATE TABLE public.venues_organizations (
    venue_organization_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    venue_id BIGINT NOT NULL REFERENCES public.venues(venue_id) ON DELETE CASCADE,
    organization_id BIGINT NOT NULL REFERENCES public.organizations(organization_id) ON DELETE CASCADE,
    display_order INTEGER NOT NULL DEFAULT 0,

    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    deleted_at TIMESTAMPTZ DEFAULT NULL
);

-- indexes
CREATE UNIQUE INDEX idx_venues_organizations_unique_active 
ON public.venues_organizations(venue_id, organization_id) 
WHERE deleted_at IS NULL;

CREATE INDEX idx_venues_organizations_display_order ON public.venues_organizations(display_order DESC);
CREATE INDEX idx_venues_organizations_venue_id ON public.venues_organizations(venue_id);
CREATE INDEX idx_venues_organizations_organization_id ON public.venues_organizations(organization_id);

-- trigger
CREATE TRIGGER update_venues_organizations
    BEFORE UPDATE ON public.venues_organizations
    FOR EACH ROW
    EXECUTE FUNCTION update_at();

-- security
ALTER TABLE public.venues_organizations ENABLE ROW LEVEL SECURITY;
CREATE POLICY "No direct access" ON public.venues_organizations FOR ALL USING (false);
REVOKE ALL ON public.venues_organizations FROM public;