-- banners table
CREATE TABLE public.banners (
    banner_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    banner_public_id UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE,
    display_order INTEGER NOT NULL DEFAULT 0,

    image TEXT NOT NULL,
    link TEXT,

    event_id BIGINT REFERENCES public.events(event_id),

    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    deleted_at TIMESTAMPTZ DEFAULT NULL
);

-- indexes
CREATE INDEX idx_banners_event_id ON public.banners(event_id);
CREATE INDEX idx_banners_display_order ON public.banners(display_order DESC);

-- trigger
CREATE TRIGGER update_banners
    BEFORE UPDATE ON public.banners
    FOR EACH ROW
    EXECUTE FUNCTION update_at();

-- security
ALTER TABLE public.banners ENABLE ROW LEVEL SECURITY;
CREATE POLICY "No direct access" ON public.banners FOR ALL USING (false);
REVOKE ALL ON public.banners FROM public;