-- categories table
CREATE TABLE public.categories (
    category_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_public_id UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE,
    display_order INTEGER NOT NULL DEFAULT 0,

    name TEXT NOT NULL,
    caption TEXT,
    icon TEXT,

    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    deleted_at TIMESTAMPTZ DEFAULT NULL
);

-- indexes
CREATE INDEX idx_category_display_order ON public.categories(display_order DESC);

-- trigger
CREATE TRIGGER update_categories
    BEFORE UPDATE ON public.categories
    FOR EACH ROW
    EXECUTE FUNCTION update_at();

-- security
ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;
CREATE POLICY "No direct access" ON public.categories FOR ALL USING (false);
REVOKE ALL ON public.categories FROM public;