-- events table
CREATE TABLE public.events (
    event_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_public_id UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE,
    display_order INTEGER NOT NULL DEFAULT 0,

    name TEXT NOT NULL,
    caption TEXT,
    icon TEXT,
    description TEXT,
    header_image TEXT,
    images TEXT[] DEFAULT '{}',

    venue_id BIGINT REFERENCES public.venues(venue_id),
    organization_id BIGINT REFERENCES public.organizations(organization_id),

    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    deleted_at TIMESTAMPTZ DEFAULT NULL
);

-- indexes
CREATE INDEX idx_event_organization_id ON public.events(organization_id);
CREATE INDEX idx_event_display_order ON public.events(display_order DESC);

-- trigger
CREATE TRIGGER update_events
    BEFORE UPDATE ON public.events
    FOR EACH ROW
    EXECUTE FUNCTION update_at();

-- security
ALTER TABLE public.events ENABLE ROW LEVEL SECURITY;
CREATE POLICY "No direct access" ON public.events FOR ALL USING (false);
REVOKE ALL ON public.events FROM public;