-- features table
CREATE TABLE public.features (
    feature_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    feature_public_id UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE,
    display_order INTEGER NOT NULL DEFAULT 0,

    name TEXT NOT NULL,
    caption TEXT,
    note TEXT,
    image TEXT,

    event_id BIGINT REFERENCES public.events(event_id),

    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    deleted_at TIMESTAMPTZ DEFAULT NULL
);

-- indexes
CREATE INDEX idx_features_event_id ON public.features(event_id);
CREATE INDEX idx_features_display_order ON public.features(display_order DESC);

-- trigger
CREATE TRIGGER update_features
    BEFORE UPDATE ON public.features
    FOR EACH ROW
    EXECUTE FUNCTION update_at();

-- security
ALTER TABLE public.features ENABLE ROW LEVEL SECURITY;
CREATE POLICY "No direct access" ON public.features FOR ALL USING (false);
REVOKE ALL ON public.features FROM public;