-- foods table
CREATE TABLE public.foods (
    food_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    food_public_id UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE,
    display_order INTEGER NOT NULL DEFAULT 0,

    name TEXT NOT NULL,
    caption TEXT,
    description TEXT,
    icon TEXT,
    minutes INTEGER,
    distance INTEGER,
    address TEXT,
    website TEXT,
    
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    deleted_at TIMESTAMPTZ DEFAULT NULL
);

-- indexes
CREATE INDEX idx_foods_display_order ON public.foods(display_order DESC);

-- trigger
CREATE TRIGGER update_foods
    BEFORE UPDATE ON public.foods
    FOR EACH ROW
    EXECUTE FUNCTION update_at();

-- security
ALTER TABLE public.foods ENABLE ROW LEVEL SECURITY;
CREATE POLICY "No direct access" ON public.foods FOR ALL USING (false);
REVOKE ALL ON public.foods FROM public;