-- news table
CREATE TABLE public.news (
    news_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    news_public_id UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE,
    display_order INTEGER NOT NULL DEFAULT 0,

    name TEXT NOT NULL,
    caption TEXT,
    description TEXT,
    header_image TEXT,
    thumbnail TEXT,
    website TEXT,

    performer_id BIGINT REFERENCES public.performers(performer_id),
    
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    deleted_at TIMESTAMPTZ DEFAULT NULL
);

-- indexes
CREATE INDEX idx_news_performer_id ON public.news(performer_id);
CREATE INDEX idx_news_display_order ON public.news(display_order DESC);

-- trigger
CREATE TRIGGER update_news
    BEFORE UPDATE ON public.news
    FOR EACH ROW
    EXECUTE FUNCTION update_at();

-- security
ALTER TABLE public.news ENABLE ROW LEVEL SECURITY;
CREATE POLICY "No direct access" ON public.news FOR ALL USING (false);
REVOKE ALL ON public.news FROM public;