-- organizations table
CREATE TABLE public.organizations (
    organization_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_public_id UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE,
    display_order INTEGER NOT NULL DEFAULT 0,

    name TEXT NOT NULL,
    caption TEXT,
    icon TEXT,
    sponsor TEXT,
    description TEXT,
    header_image TEXT,
    images TEXT[] DEFAULT '{}',

    website TEXT,
    instagram TEXT,
    linkedin TEXT,
    twitter TEXT,
    youtube TEXT,
    
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    deleted_at TIMESTAMPTZ DEFAULT NULL
);

-- indexes
CREATE INDEX idx_organization_display_order ON public.organizations(display_order DESC);

-- trigger
CREATE TRIGGER update_organizations
    BEFORE UPDATE ON public.organizations
    FOR EACH ROW
    EXECUTE FUNCTION update_at();

-- security
ALTER TABLE public.organizations ENABLE ROW LEVEL SECURITY;
CREATE POLICY "No direct access" ON public.organizations FOR ALL USING (false);
REVOKE ALL ON public.organizations FROM public;