-- performers table
CREATE TABLE public.performers (
    performer_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    performer_public_id UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE,
    display_order INTEGER NOT NULL DEFAULT 0,

    name TEXT NOT NULL,
    affiliation TEXT,
    icon TEXT,

    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    deleted_at TIMESTAMPTZ DEFAULT NULL
);

-- indexes
CREATE INDEX idx_performer_display_order ON public.performers(display_order DESC);

-- trigger
CREATE TRIGGER update_performers
    BEFORE UPDATE ON public.performers
    FOR EACH ROW
    EXECUTE FUNCTION update_at();

-- security
ALTER TABLE public.performers ENABLE ROW LEVEL SECURITY;
CREATE POLICY "No direct access" ON public.performers FOR ALL USING (false);
REVOKE ALL ON public.performers FROM public;