-- slots table
CREATE TABLE public.slots (
    slot_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slot_public_id UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE,
    display_order INTEGER NOT NULL DEFAULT 0,

    starts TIME(0) NOT NULL,
    ends TIME(0) NOT NULL,

    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    deleted_at TIMESTAMPTZ DEFAULT NULL
);

-- indexes
CREATE INDEX idx_slot_display_order ON public.slots(display_order DESC);

-- trigger
CREATE TRIGGER update_slots
    BEFORE UPDATE ON public.slots
    FOR EACH ROW
    EXECUTE FUNCTION update_at();

-- security
ALTER TABLE public.slots ENABLE ROW LEVEL SECURITY;
CREATE POLICY "No direct access" ON public.slots FOR ALL USING (false);
REVOKE ALL ON public.slots FROM public;