-- tags table
CREATE TABLE public.tags (
    tag_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tag_public_id UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE,
    display_order INTEGER NOT NULL DEFAULT 0,

    name TEXT NOT NULL,
    caption TEXT,

    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    deleted_at TIMESTAMPTZ DEFAULT NULL
);

-- indexes
CREATE INDEX idx_tag_display_order ON public.tags(display_order DESC);

-- trigger
CREATE TRIGGER update_tags
    BEFORE UPDATE ON public.tags
    FOR EACH ROW
    EXECUTE FUNCTION update_at();

-- security
ALTER TABLE public.tags ENABLE ROW LEVEL SECURITY;
CREATE POLICY "No direct access" ON public.tags FOR ALL USING (false);
REVOKE ALL ON public.tags FROM public;